apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouddetect-deployment
  labels:
    app: cloudser
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudser
  template:
    metadata:
      labels:
        app: cloudser
    spec:
      containers:
      - name: cloudsercon
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
        resources: 
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: cloudsernport
spec:
  type: NodePort
  selector: 
    app: cloudser # please specify the lables used in Deployment
  ports:
    - protocol: TCP 
      port: 1024  # the port at which the service to be indentified
      targetPort: 8080  # port in which the container is running
      nodePort: 30001 # the port in which the service is accesiable to external or end users.

